config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, shallow: true
    resources :categories, except: [:index, :create, :show, :new, :edit]
  end
  resources :categories, except: [:update, :destroy]
  root 'posts#index'
  resources :credits, only: [:index]
end


#           Prefix Verb   URI Pattern                              Controller#Action
#    post_comments GET    /posts/:post_id/comments(.:format)       comments#index
#                  POST   /posts/:post_id/comments(.:format)       comments#create
# new_post_comment GET    /posts/:post_id/comments/new(.:format)   comments#new
#     edit_comment GET    /comments/:id/edit(.:format)             comments#edit
#          comment GET    /comments/:id(.:format)                  comments#show
#                  PATCH  /comments/:id(.:format)                  comments#update
#                  PUT    /comments/:id(.:format)                  comments#update
#                  DELETE /comments/:id(.:format)                  comments#destroy
#    post_category PATCH  /posts/:post_id/categories/:id(.:format) categories#update
#                  PUT    /posts/:post_id/categories/:id(.:format) categories#update
#                  DELETE /posts/:post_id/categories/:id(.:format) categories#destroy
#            posts GET    /posts(.:format)                         posts#index
#                  POST   /posts(.:format)                         posts#create
#         new_post GET    /posts/new(.:format)                     posts#new
#        edit_post GET    /posts/:id/edit(.:format)                posts#edit
#             post GET    /posts/:id(.:format)                     posts#show
#                  PATCH  /posts/:id(.:format)                     posts#update
#                  PUT    /posts/:id(.:format)                     posts#update
#                  DELETE /posts/:id(.:format)                     posts#destroy
#             root GET    /                                        posts#index
# ~/wdi/rails_apps/four_walls_app (master)$

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations
  has_many :posts, through: :categorizations
  validates :title, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations
  has_many :comments, dependent: :destroy
  has_attached_file :image, styles: { large: "800x800>", medium: "400x400>", thumbnail: "150x150#" },
      :bucket => 'fourthwallappbucket',
                    :s3_credentials => {
                      :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
                      :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
                    }


  validates :title, :body, presence: true
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/


  def all_categories=(titles)
    categorizations = titles.split(",").map do |title|
      Category.where(title: title.strip).first_or_create!
    end
  end

  def all_categories
    categorizations.map(&:title).join(", ")
  end

  def self.tagged_with(title)
    Category.find_by_name!(title).posts
  end

  def category_titles
    categories.pluck(:name).join(", ")
  end

  def category_titles=(titles)
    categories = titles.split(",").map { |category| Category.where(title: category.squish).first_or_create! }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    redirect_to category_path(@category)
  end

  private

    def category_params
      params.require(:category).permit(:title)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
  end

  def new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.post = Post.find(params[:post_id])
    if @comment.save
      redirect_to post_path(@comment.post_id)
    else
      flash[:error] = "Comment can't be blank"
      redirect_to post_path(@comment.post_id)
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to post_path(@comment.post_id)
    else
      flash[:error] = "Comment can't be blank"
      redirect_to post_path(@comment.post_id)
    end
  end

  def destroy
    post = @comment.post
    @comment.destroy
    redirect_to post_path(post.id)
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :image)
  end

  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      flash[:success] = 'Post successfully created'
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(post_params)
      flash[:success] = 'Post successfully updated.'
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = 'Post successfully deleted.'
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image, :comments, :categories, :all_categories)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="<%= key %>">
    <%= message %>
  </div>
<% end %>

app/views/categories/_catagories.html.erb
<% @categories.all.each do |cat| %>
<div>
<%= cat.title %><br>
</div>
<% end %>

app/views/categories/_form.html.erb
<div>
  <%= form_for @category  do |f| %>
    <div>
      <%= f.label :title %>
    </div>
    <div>
      <%= f.text_area :title %>
    </div>
    <div>
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/categories/index.html.erb
<div class="categories-main">
<% @categories.all.each do |cat| %>
<div ><%= link_to cat.title, category_path(cat), :class => "category-element" %>
</div>
<% end %>
</div>
<div class="category-link-container">
<%= link_to 'new', new_category_path, :class => "category-link" %><br>
</div>

app/views/categories/new.html.erb
<div>
<%= render 'form' %>
</div>

app/views/categories/show.html.erb
<% @category.posts.each do |post| %>
  <div class="category">
  <%= link_to post.title, post_path(post) %>
  <%= image_tag post.image.url(:thumbnail) %>
<%end%>

app/views/comments/_form.html.erb
<div class="form-container">
<%= form_for [@post, @comment] do |f| %>
<div>
    <%= f.label :body, :class => "form" %>
  </div>
  <div>
    <%= f.text_area :body, :class => "form" %>
  </div>
  <div>
    <%= f.submit %>
    </div>
<% end %>
</div>

app/views/credits/index.html.erb
<div class="credit-banner-container">
  <div class="credit-banner">@charlietal</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FourWallsApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="header">
      <%= link_to 'FOUR WALLS', root_path, :class => "logo" %>
    </nav>


    <div class="left-nav-bar">
      <div class="site-link"><%= link_to 'NEW POST', new_post_path, :class => "left-nav-element" %></div>
      <div class="site-link"><%= link_to 'c a t e g o r y | c a t e g o r y | c a t e g o r y', categories_path, :class => "left-nav-element" %></div>
      <div class="site-link"><%= link_to '¿¿¿???', credits_path, :class => "nav-elements" %></div>
    </div>

    <%= render 'flash' %>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="form-container">
  <%= form_for @post, html: { multipart: true } do |f| %>
    <div>
      <%= f.label :title, :class => "form-label" %>
      <%= f.text_field :title, :class => "form" %>
    </div>
    <div>
      <%= f.label :body, :class => "form-label" %>
      <%= f.text_area :body, :class => "form" %>
    </div>
    <div>
      <%= f.label :artist, :class => "form-label" %>
      <%= f.text_area :artist, :class => "form" %>
    </div>
    <div>
      <%= f.label :image, :class => "form-label" %>
      <%= f.file_field :image, :class => "form-btn" %>
    </div>
    <div>
      <%= f.submit :class => "submit-btn" %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="new-post-main-div">
  <div class="new-post-header">
  <h1>Edit Post</h1>
  </div>
  <div class="new-post-form">
  <%= render 'form' %>
  </div>
  <%= link_to 'Delete Post', post_path(@post),
              method: :delete,
              data: { confirm: 'Are you sure?' }%>
</div>

app/views/posts/index.html.erb
<head>
  <title>artposts</title>
</head>

<body>
  <div class="home-index-wrapper">

    <h1 class="title">  </h1>

    <div class="posts-left">
      <table class="posts-index">
        <% @posts.reverse.each do |post| %>
        <div>
          <div class="posts">
          <%= link_to post_path(post) do %>
            <%= image_tag post.image.url(:medium) %><br>
            <% end %>

            <div class="post-title"><%= post.title %></div>
            <div class="post-body">
              <p><%= post.body %></p>
              <p><%= post.artist %></p>
              <p><%= post.venue %></p>
            </div>
          </div>
        </div>
        <% end %>
      </table>
    </div>
  </div>
</body>

app/views/posts/new.html.erb
<div class="new-post-main-div">
  <div class="new-post-header">
  <h1>New Post</h1>
  </div>
  <div class="new-post-form">
  <%= render 'form' %>
  </div>
</div>

app/views/posts/show.html.erb
<head></head>
<body>

<div class="posts-left">
  <h1 class="post-show"><%= @post.title %></h1>

  <div class="posts"><%= image_tag @post.image.url(:large) %></div>
  <div class="show-post-title"><%= @post.title %>|<%= @post.body %><br></div>
  <div class="show-link"><%= link_to 'Back', posts_path %> | <%= link_to 'Edit', edit_post_path(@post) %></div>

  <%= form_for [@post, @post.comments.new] do |f| %>
  <div class="comment-form">
      <%= f.label 'post comment', :class => "comment-label" %>
      <%= f.text_area :body, :class => "comment-field" %>

      <%= f.submit %>
    <% end %>
  </div>
  </div>
  <div class="post-comments-container">
    <% @post.comments.each do |comment| %>
    <div class="post-comments"><%= comment.body %>
    </div>
    <% end %>
  </div>
  <div class="post-categories-container">
  <% @post.categories.each do |category| %>
  <div class="post-categories">
    <%= link_to category.title, category_path(category.id), :class => "bonkers" %>
  </div>
    <%end%>
  </div>

</body>